version: 2.1

description: |
  Install and run reviewdog (https://github.com/haya14busa/reviewdog).
  You can run linter using run_linter_steps before reviewdog.
  Now, support only GitHub. You should define REVIEWDOG_GITHUB_API_TOKEN environment in your circleci project.
  This orb is mainted in https://github.com/yasuhiroki/circleci-reviewdog-orb

executors:
  default:
    description: |
      To run your linter and reviewdog Docker container.
      note) Reviewdog is instlaled by wget command, so this container should be able to use wget.
    parameters:
      linter_image:
        description: Specify your linter tool executable image
        type: string
        default: alpine:latest
    docker:
      - image: <<parameters.linter_image>>

jobs:
  reviewdog:
    parameters:
      linter_image:
        description: Linter executable image
        type: string
        default: alpine:latest
      reviewdog_version:
        description: Reviewdog version
        type: string
        default: 0.9.11
      reviewdog_format_option:
        description: Reviewdog format options
        type: string
      run_linter_steps:
        description: Run linter steps
        type: steps
      lint_result_file_path:
        description: Linter output result file path
        type: string
    executor:
      name: default
      linter_image: <<parameters.linter_image>>
    steps:
      - steps: <<parameters.run_linter_steps>>
      - run: |
          test -f /usr/local/bin/reviewdog \
            || \
          wget https://github.com/haya14busa/reviewdog/releases/download/<<parameters.reviewdog_version>>/reviewdog_linux_amd64 -O /usr/local/bin/reviewdog \
            && \
          chmod +x /usr/local/bin/reviewdog
      - run: |
          test ${CI_PULL_REQUEST} || exit 0
          cat <<parameters.lint_result_file_path>> | reviewdog <<parameters.reviewdog_format_option>> -reporter=github-pr-review

examples:
  rubocop:
    description: |
      Run rubocop and reviewdog
    usage:
      orbs:
        reviewdog: yasuhiroki/reviewdog@0.0.3
      commands:
        lint:
          parameters:
            lint_result_file_path:
              description: Lint result file path
              type: string
          steps:
            - checkout
            - run: rubocop --out <<parameters.lint_result_file_path>> || true
            - store_artifacts:
                path: <<parameters.lint_result_file_path>>
      version: 2.1
      workflows:
        main:
          jobs:
            - reviewdog/reviewdog:
                linter_image: cagedata/rubocop
                reviewdog_format_option: -f=rubocop
                run_linter_steps:
                  - lint:
                      lint_result_file_path: res.txt
                lint_result_file_path: res.txt

