description: |
  To run your linter and reviewdog Docker container.
  note) Reviewdog is instlaled by curl command, so this container should be able to use curl.
docker:
  - image: <<parameters.linter_image>>
parameters:
  linter_image:
    description: Specify your linter tool executable image
    type: string
    default: golang:latest

